import {readFile,writeFile} from 'node:fs/promises';
const md=await readFile('DESIGN.md','utf8');
const colorBlock=md.split('\ncolors:\n')[1].split('\ntypography:')[0];
const colors=Object.fromEntries([...colorBlock.matchAll(/^  ([a-z-]+): "(#[A-Fa-f0-9]+)"/gm)].map(m=>[m[1],m[2]]));
// Tonal ramps are panel metadata, not additional shipping primitive colours.
function lch(hex){const [r,g,b]=hex.match(/[\da-f]{2}/gi).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);const l=Math.cbrt(.4122214708*r+.5363325363*g+.0514459929*b),m=Math.cbrt(.2119034982*r+.6806995451*g+.1073969566*b),s=Math.cbrt(.0883024619*r+.2817188376*g+.6299787005*b);const a=1.9779984951*l-2.428592205*m+.4505937099*s,bb=.0259040371*l+.7827717662*m-.808675766*s;return {c:Math.sqrt(a*a+bb*bb),h:(Math.atan2(bb,a)*180/Math.PI+360)%360};}
const labels={primary:'Index violet','primary-deep':'Violet deep',context:'Lilac',paper:'Paper',ink:'Ink',muted:'Muted',line:'Line',surface:'Surface','dark-muted':'Dark secondary','dark-line':'Dark line','dark-accent':'Dark active','dark-surface':'Dark surface','dark-context':'Dark context',positive:'Positive','positive-surface':'Positive surface'};
const colorMeta=Object.fromEntries(Object.entries(colors).map(([name,hex])=>{const {c,h}=lch(hex);return [name,{role:['primary','primary-deep','context'].includes(name)?'primary':'neutral',displayName:labels[name],canonical:hex,tonalRamp:[15,25,35,45,55,70,85,95].map(l=>`oklch(${l}% ${c.toFixed(4)} ${h.toFixed(2)})`)}];}));
const overview=md.split('**Creative North Star: "The Work Index"**\n\n')[1].split('\n\n**Key Characteristics:**')[0];
const characteristics=md.split('**Key Characteristics:**\n\n')[1].split('\n\n## Colors')[0].split('\n').filter(l=>l.startsWith('- ')).map(l=>l.slice(2));
const bullets=header=>md.split(header+'\n\n')[1].split('\n\n')[0].split('\n').map(l=>l.replace(/^- /,'').replaceAll('**',''));
const components=[
  {name:'Primary button',kind:'button',refersTo:'button-primary',description:'Violet action with a readable label and explicit focus.',html:'<button class="ds-primary">Explore the Work Index</button>',css:'.ds-primary{font-family:"Source Sans 3",sans-serif;font-size:16px;font-weight:600;background:var(--color-violet,#6038E8);color:var(--color-paper,#FFFFFF);padding:15px 24px;min-height:48px;border:0;border-radius:4px;cursor:pointer;transition:background 180ms cubic-bezier(.16,1,.3,1)}.ds-primary:hover{background:var(--color-violet-deep,#4825BC)}.ds-primary:focus-visible{outline:3px solid var(--color-violet,#6038E8);outline-offset:5px}.ds-primary:active{background:var(--color-violet-deep,#4825BC)}'},
  {name:'Source selection',kind:'input',description:'Native checkbox with source name and type.',html:'<label class="ds-source"><input type="checkbox" checked><span><strong>Opening brief</strong><small>Page · purpose and opening plan</small></span></label>',css:'.ds-source{display:flex;align-items:center;gap:12px;padding:14px 16px;background:var(--color-paper,#FFFFFF);color:var(--color-ink,#191922);border:1px solid #D7CFF5;border-radius:4px;font-family:"Source Sans 3",sans-serif;cursor:pointer}.ds-source input{width:18px;height:18px;accent-color:var(--color-violet,#6038E8)}.ds-source strong{display:block;font-size:15px;font-weight:600}.ds-source small{display:block;font-size:12px;color:var(--color-muted,#656572)}.ds-source:hover{border-color:var(--color-violet,#6038E8)}.ds-source input:focus-visible{outline:3px solid var(--color-violet,#6038E8);outline-offset:5px}'},
  {name:'Status',kind:'chip',refersTo:'status',description:'Written status; colour and dot are supplementary.',html:'<span class="ds-status">In progress</span>',css:'.ds-status{display:inline-flex;align-items:center;padding:4px 9px;border-radius:4px;font:600 13px "Source Sans 3",sans-serif;background:var(--color-lilac,#F0ECFD);color:var(--color-violet-deep,#4825BC)}.ds-status:before{content:"";width:5px;height:5px;margin-right:6px;border-radius:50%;background:currentColor}'},
  {name:'Chapter navigation',kind:'nav',description:'Native links with an active violet rule.',html:'<nav class="ds-nav" aria-label="Brand chapters"><a href="#introduction" tabindex="0" aria-current="location">Introduction</a><a href="#story" tabindex="0">Story</a><a href="#logo" tabindex="0">Logo</a></nav>',css:'.ds-nav{display:flex;gap:24px;flex-wrap:wrap;font:15px "Source Sans 3",sans-serif}.ds-nav a{display:flex;align-items:center;min-height:32px;text-decoration:none;border-bottom:1px solid transparent;color:var(--color-ink,#191922)}.ds-nav a[aria-current],.ds-nav a:hover{color:var(--color-violet,#6038E8)}.ds-nav a[aria-current]{border-color:var(--color-violet,#6038E8)}.ds-nav a:focus-visible{outline:3px solid var(--color-violet,#6038E8);outline-offset:5px}'},
  {name:'Context panel',kind:'card',refersTo:'context-panel',description:'Lilac field with a white explanatory response.',html:'<div class="ds-context"><h3>From information to understanding.</h3><p class="ds-response">This explanation uses the sources you selected.</p></div>',css:'.ds-context{background:var(--color-lilac,#F0ECFD);color:var(--color-ink,#191922);padding:32px;border-radius:4px;font-family:"Source Sans 3",sans-serif}.ds-context h3{font-family:Archivo,sans-serif;font-size:28px;line-height:1.2;letter-spacing:-.025em;margin:0}.ds-response{font-size:16px;line-height:1.6;padding:24px;background:var(--color-paper,#FFFFFF);border-radius:4px;margin:24px 0 0}'},
  {name:'Index row',kind:'custom',description:'Indexed source name with a description and native link.',html:'<a class="ds-index" href="#opening-brief" tabindex="0"><span class="ds-number">01</span><span><strong>Opening brief</strong><small>Purpose, scope, and opening plan</small></span></a>',css:'.ds-index{display:flex;align-items:center;gap:16px;padding:16px 0;border-bottom:1px solid var(--color-line,#DCDCE5);text-decoration:none;color:var(--color-ink,#191922);font-family:"Source Sans 3",sans-serif}.ds-number{color:var(--color-violet,#6038E8);font-size:14px;min-width:20px;font-variant-numeric:tabular-nums}.ds-index strong{display:block;font-size:16px;font-weight:600}.ds-index small{display:block;font-size:14px;color:var(--color-muted,#656572);margin-top:3px}.ds-index:hover{color:var(--color-violet,#6038E8);background:var(--color-surface,#F7F7FA)}.ds-index:focus-visible{outline:3px solid var(--color-violet,#6038E8);outline-offset:5px}'}
];
const sidecar={schemaVersion:2,generatedAt:new Date().toISOString(),title:'Design System: Monolith',extensions:{colorMeta,typographyMeta:{display:{displayName:'Archivo display',purpose:'Leading identity phrase.'},headline:{displayName:'Archivo headline',purpose:'Section ideas.'},title:{displayName:'Archivo title',purpose:'Component titles.'},body:{displayName:'Source Sans 3 reading',purpose:'Explanatory copy and interface content.'},label:{displayName:'Source Sans 3 label',purpose:'Concise source, status and utility names.'}},shadows:[],motion:[{name:'state',value:'180ms',purpose:'Colour and background state changes.'},{name:'ease-out',value:'cubic-bezier(.16,1,.3,1)',purpose:'Exponential easing.'},{name:'index-arrive',value:'850ms',purpose:'Already-visible hero label gathering.'},{name:'index-offsets',value:'0ms, 100ms, 200ms',purpose:'Three labels gather sequentially.'},{name:'reduced-motion',value:'none',purpose:'Disable non-essential animation, transition and smooth scrolling.'}],breakpoints:[{name:'compact',value:'760px'},{name:'medium',value:'1100px'},{name:'wide',value:'1600px'}]},components,narrative:{northStar:'The Work Index',overview,keyCharacteristics:characteristics,rules:[{name:'The Context Rule',body:'Accent means selection, relationship or action; a selected source retains a visible name and a source link.',section:'colors'}],dos:bullets('### Do:'),donts:bullets("### Don't:")}};
await writeFile('.impeccable/design.json',JSON.stringify(sidecar,null,2)+'\n');
console.log('Wrote schema-2 design extensions and six self-contained component examples from the finished system.');
